create or replace TABLE ROOT_DEPTH (
	ROOT_DEPTH_ID NUMBER(1,0),
	ROOT_DEPTH_CODE VARCHAR(1),
	ROOT_DEPTH_NAME VARCHAR(7),
	UNIT_OF_MEASURE VARCHAR(2),
	RANGE_MIN NUMBER(2,0),
	RANGE_MAX NUMBER(2,0)
);