name: garden_plants_deploy_to_production

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'Garden_Plants_DB/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3       
     # - uses: actions/setup-python@v4

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_PRD_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_PRD_USERNAME }}
          SF_ROLE: ${{ secrets.SF_PRD_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_PRD_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_PRD_DATABASE  }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PRD_PASSWORD }}   
          SF_CHANGE_HISTORY_TABLE: "${{ secrets.SF_PRD_DATABASE  }}.SCHEMACHANGE.CHANGE_HISTORY"
        run: |
          echo "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          python -m pip install schemachange  --upgrade
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE\Garden_Plants_DB -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_CHANGE_HISTORY_TABLE --create-change-history-table
