name: snowflake_export_to_stage

# this workflow will run when the identified workflow below has completed
on:
  workflow_run:
    workflows: ["garden_plants_deploy_to_stage"]
    types:
      - completed
      
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# this will need to be updated to our self hosted runner
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo content
        uses: actions/checkout@v3  
   
#these python and pip and snowflake installs will likely need to be done directly on the IU runner so will need to be commented out when we go to IU. 
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

#these python and pip and snowflake installs will likely need to be done directly on the IU runner so will need to be commented out when we go to IU. 
      - name: install python packages
        run: |
          python -m pip install --upgrade pip

#these python and pip and snowflake installs will likely need to be done directly on the IU runner so will need to be commented out when we go to IU. 
      - name: Install snowflake-connector-python
        run: |
          python -m pip install snowflake-connector-python

# execute script and leverage secrets - these will be passed to the python script
      - name: execute py script # run script
        env:
          SF_STG_ACCOUNT: ${{ secrets.SF_STG_ACCOUNT }}
          SF_STG_USERNAME: ${{ secrets.SF_STG_USERNAME }}
          SF_STG_ROLE: ${{ secrets.SF_STG_ROLE }}
          SF_STG_WAREHOUSE: ${{ secrets.SF_STG_WAREHOUSE }}
          SF_STG_DATABASE: ${{ secrets.SF_STG_DATABASE  }}
          SF_STG_PASSWORD: ${{ secrets.SF_STG_PASSWORD }}   

# path to the python script to run
        run: | 
         python Export_Scripts/snowflake_export.py

# This step configures Git, stages the specific directory, commits, and pushes it to the 'stage' branch.     
      - name: Commit DDL to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Snowflake_Export/  
          current_date_time=$(TZ="America/New_York" date +"%Y-%m-%d %H:%M:%S")
          git diff-index --quiet HEAD || git commit -m "Snowflake Export - $current_date_time"  # Commit only if there are changes.
          git push origin stage
